[package]
name = "galactic_strike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.0-rc0"
half = "2.3.1"
png = "0.17.10"
rand = "0.8.5"
